{"name": "添加联系人", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '.././data/screenshot.png'", "trace": "self = <testcase.test_add_contact.TestAddContacts object at 0x7fd438a44a60>\ncookies_driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"2a54320f9606cbb502904e8d7559e280\")>\n\n    @allure.title('添加联系人')\n    @allure.story('添加联系人')\n    def test_add_contcats(self,cookies_driver):\n        cookies_driver.get(\"https://work.weixin.qq.com/wework_admin/frame#contacts\")\n        cookies_driver.refresh()\n    \n        # 打开通讯录\n        cookies_driver.find_element_by_id('menu_contacts').click()\n        time.sleep(2)\n    \n        # 点击添加成员按钮\n        with allure.step('点击添加成员按钮'):\n            add_btn = cookies_driver.find_element_by_xpath('//div[@class=\"ww_operationBar\"]/a[contains(@class,\"js_add_member\")]')\n            add_btn.click()\n            time.sleep(4)\n    \n        # 填入成员信息\n        with allure.step('填入成员信息'):\n            user_name = \"测试人员1\"\n            cookies_driver.find_element_by_id(\"username\").send_keys(user_name)\n            cookies_driver.find_element_by_id(\"memberAdd_english_name\").send_keys(\"1号\")\n            cookies_driver.find_element_by_id(\"memberAdd_acctid\").send_keys(\"Cs01\")\n            cookies_driver.find_element_by_id(\"memberAdd_phone\").send_keys(\"13004445461\")\n            cookies_driver.find_element_by_id(\"memberAdd_title\").send_keys(\"普通职员\")\n            time.sleep(2)\n    \n            # 保存信息\n            cookies_driver.find_element_by_css_selector(\n                '.js_member_editor_form > div:nth-child(1) .js_btn_save').click()\n    \n            # 断言通讯录是否添加成功e\n            with allure.step(\"断言添加结果\"):\n                user_list = cookies_driver.find_elements_by_css_selector(f'[title=\"{user_name}\"]')\n                assert len(user_list) >= 1, \"成员添加失败\"\n                cookies_driver.save_screenshot(\".././data/screenshot.png\")\n>               allure.attach.file(\".././data/screenshot.png\", name='通讯录结果截图', attachment_type=allure.attachment_type.PNG)\n\ntestcase/test_add_contact.py:59: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/allure_commons/_allure.py:182: in file\n    plugin_manager.hook.attach_file(source=source, name=name, attachment_type=attachment_type, extension=extension)\n/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/manager.py:84: in <lambda>\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\n/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/allure_pytest/listener.py:226: in attach_file\n    self.allure_logger.attach_file(uuid4(), source, name=name, attachment_type=attachment_type, extension=extension)\n/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/allure_commons/reporter.py:114: in attach_file\n    plugin_manager.hook.report_attached_file(source=source, file_name=file_name)\n/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/hooks.py:286: in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/manager.py:93: in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/manager.py:84: in <lambda>\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\n/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/allure_commons/logger.py:53: in report_attached_file\n    shutil.copy2(source, destination)\n/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shutil.py:435: in copy2\n    copyfile(src, dst, follow_symlinks=follow_symlinks)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nsrc = '.././data/screenshot.png'\ndst = '/Volumes/data/Python/third_homework/result/2482320e-5629-4e05-96b6-64beb60264de-attachment.png'\n\n    def copyfile(src, dst, *, follow_symlinks=True):\n        \"\"\"Copy data from src to dst in the most efficient way possible.\n    \n        If follow_symlinks is not set and src is a symbolic link, a new\n        symlink will be created instead of copying the file it points to.\n    \n        \"\"\"\n        sys.audit(\"shutil.copyfile\", src, dst)\n    \n        if _samefile(src, dst):\n            raise SameFileError(\"{!r} and {!r} are the same file\".format(src, dst))\n    \n        file_size = 0\n        for i, fn in enumerate([src, dst]):\n            try:\n                st = _stat(fn)\n            except OSError:\n                # File most likely does not exist\n                pass\n            else:\n                # XXX What about other special files? (sockets, devices...)\n                if stat.S_ISFIFO(st.st_mode):\n                    fn = fn.path if isinstance(fn, os.DirEntry) else fn\n                    raise SpecialFileError(\"`%s` is a named pipe\" % fn)\n                if _WINDOWS and i == 0:\n                    file_size = st.st_size\n    \n        if not follow_symlinks and _islink(src):\n            os.symlink(os.readlink(src), dst)\n        else:\n>           with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:\nE           FileNotFoundError: [Errno 2] No such file or directory: '.././data/screenshot.png'\n\n/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shutil.py:264: FileNotFoundError"}, "steps": [{"name": "点击添加成员按钮", "status": "passed", "start": 1629042021868, "stop": 1629042025928}, {"name": "填入成员信息", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '.././data/screenshot.png'\n", "trace": "  File \"/Volumes/data/Python/third_homework/testcase/test_add_contact.py\", line 59, in test_add_contcats\n    allure.attach.file(\".././data/screenshot.png\", name='通讯录结果截图', attachment_type=allure.attachment_type.PNG)\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/allure_commons/_allure.py\", line 182, in file\n    plugin_manager.hook.attach_file(source=source, name=name, attachment_type=attachment_type, extension=extension)\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/hooks.py\", line 286, in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/manager.py\", line 93, in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/manager.py\", line 84, in <lambda>\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/callers.py\", line 208, in _multicall\n    return outcome.get_result()\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/callers.py\", line 80, in get_result\n    raise ex[1].with_traceback(ex[2])\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/allure_pytest/listener.py\", line 226, in attach_file\n    self.allure_logger.attach_file(uuid4(), source, name=name, attachment_type=attachment_type, extension=extension)\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/allure_commons/reporter.py\", line 114, in attach_file\n    plugin_manager.hook.report_attached_file(source=source, file_name=file_name)\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/hooks.py\", line 286, in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/manager.py\", line 93, in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/manager.py\", line 84, in <lambda>\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/callers.py\", line 208, in _multicall\n    return outcome.get_result()\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/callers.py\", line 80, in get_result\n    raise ex[1].with_traceback(ex[2])\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/allure_commons/logger.py\", line 53, in report_attached_file\n    shutil.copy2(source, destination)\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shutil.py\", line 435, in copy2\n    copyfile(src, dst, follow_symlinks=follow_symlinks)\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shutil.py\", line 264, in copyfile\n    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:\n"}, "steps": [{"name": "断言添加结果", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '.././data/screenshot.png'\n", "trace": "  File \"/Volumes/data/Python/third_homework/testcase/test_add_contact.py\", line 59, in test_add_contcats\n    allure.attach.file(\".././data/screenshot.png\", name='通讯录结果截图', attachment_type=allure.attachment_type.PNG)\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/allure_commons/_allure.py\", line 182, in file\n    plugin_manager.hook.attach_file(source=source, name=name, attachment_type=attachment_type, extension=extension)\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/hooks.py\", line 286, in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/manager.py\", line 93, in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/manager.py\", line 84, in <lambda>\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/callers.py\", line 208, in _multicall\n    return outcome.get_result()\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/callers.py\", line 80, in get_result\n    raise ex[1].with_traceback(ex[2])\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/allure_pytest/listener.py\", line 226, in attach_file\n    self.allure_logger.attach_file(uuid4(), source, name=name, attachment_type=attachment_type, extension=extension)\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/allure_commons/reporter.py\", line 114, in attach_file\n    plugin_manager.hook.report_attached_file(source=source, file_name=file_name)\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/hooks.py\", line 286, in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/manager.py\", line 93, in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/manager.py\", line 84, in <lambda>\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/callers.py\", line 208, in _multicall\n    return outcome.get_result()\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/callers.py\", line 80, in get_result\n    raise ex[1].with_traceback(ex[2])\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/allure_commons/logger.py\", line 53, in report_attached_file\n    shutil.copy2(source, destination)\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shutil.py\", line 435, in copy2\n    copyfile(src, dst, follow_symlinks=follow_symlinks)\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shutil.py\", line 264, in copyfile\n    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:\n"}, "attachments": [{"name": "通讯录结果截图", "source": "2482320e-5629-4e05-96b6-64beb60264de-attachment.png", "type": "image/png"}], "start": 1629042028264, "stop": 1629042029012}], "start": 1629042025928, "stop": 1629042029018}], "start": 1629042016503, "stop": 1629042029018, "uuid": "f52bb2ad-be5f-420a-bcaa-cd47537e8185", "historyId": "f7de7e4e427ef623cf88a11df011d9c0", "testCaseId": "88150ff729f4a501b7449b3dfdddc7ab", "fullName": "test_add_contact.TestAddContacts#test_add_contcats", "labels": [{"name": "story", "value": "添加联系人"}, {"name": "feature", "value": "企业微信web测试"}, {"name": "suite", "value": "test_add_contact"}, {"name": "subSuite", "value": "TestAddContacts"}, {"name": "host", "value": "liuyaodeiMac"}, {"name": "thread", "value": "5878-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_add_contact"}]}